// Code generated by Kitex v0.12.1. DO NOT EDIT.
package articleservice

import (
	server "github.com/cloudwego/kitex/server"
	article "github.com/lianzhilu/chat-paper/cp-core/kitex/kitex_gen/article"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler article.ArticleService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler article.ArticleService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
